######### Basic Settings #########
basic:
    device: '6'
    seed: [1] # 1, 50, 42, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: path16
    shuffle: false

    # Method Choises: 
    method: finetune_normal
    method_type: single_step
    # eval_metric Choises: acc, mcr
    eval_metric: acc
    openset_test: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    freeze_fe: false
    save_models: true # if true, programm will save model's weights during incremental train

    note: pretrain_lr0.001_order5

######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    path16:
        resnet18:
            img_size: 224

            epochs: 200 # 200
            batch_size: 32
            num_workers: 8
            
            opt_type: sgd
            lrate: 0.0001
            weight_decay: 0.0005
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            