######### Basic Settings #########
basic:
    device: '3'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: podnet
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: cosine_resnet32
    pretrained: false
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean

    apply_nme: true

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 50
    increment: 10


######### Method's Hyperparameters #########
special:
    incre_type: cil
    lambda_c_base: 5
    lambda_f_base: 1
    nb_proxy: 10

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        cosine_resnet32:
            opt_type: sgd
            scheduler: cos
            epochs: 160 # 160
            lrate: 0.1
            batch_size: 128
            weight_decay: 0.0005
            
            epochs_finetune: 20
            lrate_finetune: 0.005

            layer_names: ['stage_1', 'stage_2', 'stage_3']

            num_workers: 4
            
