######### Basic Settings #########
basic:
    device: '0'
    seed: [1993]

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar10
    shuffle: true

    # Method Choises: 
    method: finetune_normal
    method_type: single_step
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18_cbam
    pretrained: true
    freeze_fe: true
    save_models: false # if true, programm will save model's weights during incremental train

    note: linear_tune_eff

    # for more efficient experiment
    split_dataset: true
    init_cls: 10
    increment: 10

######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:
    cifar10: 
        resnet18_cbam:
            pretrain_path: pretrain_weights/imagenet200_resnet18_cbam_pretrained.pth
            
            epochs: 200 #80
            batch_size: 128
            num_workers: 8
            
            opt_type: adam
            lrate: 0.001
            
            scheduler: multi_step
            milestones: [60,120,160]
            lrate_decay: 0.1
            
