######### Basic Settings #########
basic:
    device: '2'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar10
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: finetune_il
    method_type: multi_steps
    incre_type: cil
    # eval_metric Choises: acc, recall
    eval_metric: acc

    apply_nme: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet32
    pretrained: false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 2
    increment: 2

    logger_type: tensorboard

    note: test
    # test_epoch: 10

######### Method's Hyperparameters #########
special:
    incre_type: cil

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar10: 
        resnet32:
            epochs: 3 #80
            batch_size: 128
            num_workers: 8

            opt_type: sgd
            lrate: 0.1
            weight_decay: 0.0002
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [40, 70]
            lrate_decay: 0.1
            
