######### Basic Settings #########
basic:
    device: '1'
    seed: [100, 1993] # 42, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: path16
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: finetune_il
    method_type: multi_steps
    # eval_metric Choises: acc, mcr
    eval_metric: acc
    openset_test: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true

    note: pretrained_lr0.001

######### Method's Hyperparameters #########
special:
    incre_type: cil
    
######### Experiment Settings for Datasets #########
options:
    path16:        
        resnet18:
            img_size: 224
            
            epochs: 200 # 200
            batch_size: 32
            num_workers: 8

            opt_type: sgd
            lrate: 0.001
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
