######### Basic Settings #########
basic:
    device: '6'
    seed: [1] # 1993, 42, 100

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: pretrain_sd158
    shuffle: false

    # Method Choises: 
    method: finetune_normal
    method_type: single_step
    # eval_metric Choises: acc, mcr
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: efficientnet_b0
    pretrained: true
    freeze_fe: false
    save_models: true # if true, programm will save model's weights during incremental train

    note: pretrain_sd158_epoch200_lr0.0001

######### Method's Hyperparameters #########
# special:
    

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    pretrain_sd158:
        resnet18:
            img_size: 224
            opt_type: adam
            epochs: 200 # 200
            lrate: 0.01
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            batch_size: 32
            num_workers: 4
        
        resnet50:
            img_size: 224
            opt_type: adam
            epochs: 200 # 200
            lrate: 0.0001
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            batch_size: 32
            num_workers: 4
        
        mobilenet_v2:
            img_size: 224
            opt_type: adam
            epochs: 200 # 200
            lrate: 0.0001
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            batch_size: 32
            num_workers: 4
        
        efficientnet_b0:
            img_size: 224
            opt_type: adam
            epochs: 200 # 200
            lrate: 0.0001
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            batch_size: 32
            num_workers: 4

        # vgg16_bn:
        #     img_size: 224
        #     opt_type: adam
        #     epochs: 200 # 200
        #     lrate: 0.001
        #     scheduler: multi_step
        #     milestones: [70, 130, 170]
        #     lrate_decay: 0.1
        #     batch_size: 32
        #     num_workers: 4
        