######### Basic Settings #########
basic:
    device: '0'
    seed: [1] # [42, 100, 1993]

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: mymedmnist
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dynamic_er
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18
    backbone: resnet18
    pretrained: true # false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 200
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true

    note: seed1_batch64

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 5

######### Experiment Settings for Datasets #########
options:
    mymedmnist:
        resnet18:
            img_size: 224

            epochs: 100 # 170
            batch_size: 64
            num_workers: 8

            opt_type: sgd
            lrate: 0.005
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [60, 80]
            lrate_decay: 0.1
            
            epochs_finetune: 50 # 200
            lrate_finetune: 0.005
            milestones_finetune: [35]