######### Basic Settings #########
basic:
    device: '0'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: false

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dark_er
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18
    backbone: resnet18_cifar
    pretrained: false # false
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: reservoir # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10

    note: der_pp

######### Method's Hyperparameters #########
special:
    incre_type: cil
    alpha: 0.1
    beta: 0.5

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet18_cifar:
            img_size: 32

            epochs: 50 # 170
            batch_size: 32
            num_workers: 4  
            
            opt_type: sgd
            lrate: 0.03 # 0.03
            weight_decay: 0
            opt_mom: 0

            scheduler: multi_step
            milestones: [35, 45]
            lrate_decay: 0.1
            