######### Basic Settings #########
basic:
    device: '2'
    seed: [42] # 42, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin40
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: dual_distill
    method_type: multi_steps
    # eval_metric Choises: acc, mcr
    eval_metric: acc
    openset_test: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 50
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    apply_nme: true

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10
    
    note: no_pretrained_buffer50_lr0.001

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 4
    alpha: 3.0
    beta: 1.0

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin40:
        resnet18:
            img_size: 224
            # opt_type: adam
            opt_type: sgd
            weight_decay: 0.0005
            epochs: 200 # 200
            lrate: 0.001
            scheduler: multi_step
            milestones: [80, 160]
            lrate_decay: 0.1
            batch_size: 16
            num_workers: 4
        