######### Basic Settings #########
basic:
    device: '1'
    seed: [1993] # 42, 100, 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: true # true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: acl
    method_type: multi_steps
    # eval_metric Choises: acc, mcr
    eval_metric: acc
    openset_test: true

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: true
    freeze_fe: true
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10
    
    logger_type: tensorboard
    # test_epoch: 10

######### Method's Hyperparameters #########
special:
    incre_type: cil

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100:
        resnet18:
            img_size: 224

            layer_names: ['layer1', 'layer2', 'layer3', 'layer4']
            
            epochs: 200 # 200
            batch_size: 32
            num_workers: 4

            opt_type: sgd
            lrate: 0.01
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
            epochs_finetune: 50 # 50
            lrate_finetune: 0.001
            milestones_finetune: [15, 35]
        
        mobilenet_v2:
            img_size: 224
            
            layer_names: ['features.3', 'features.5', 'features.12', 'features.15']
            
            epochs: 200 # 200
            batch_size: 32
            num_workers: 4

            opt_type: sgd
            lrate: 0.01
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
            epochs_finetune: 100 # 50
            lrate_finetune: 0.001
            milestones_finetune: [15, 35]
        
        efficientnet_b0:
            img_size: 224
            
            layer_names: ['features.4', 'features.5', 'features.6', 'features.8']
            
            epochs: 200 # 200
            batch_size: 32
            num_workers: 4

            opt_type: sgd
            lrate: 0.01
            weight_decay: 0.0005
            opt_mom: 0.9
            
            scheduler: multi_step
            milestones: [70, 130, 170]
            lrate_decay: 0.1
            
            epochs_finetune: 100 # 50
            lrate_finetune: 0.001
            milestones_finetune: [15, 35]