######### Basic Settings #########
basic:
    device: '4'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: l2p
    method_type: multi_steps
    incre_type: cil
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: vit_base_patch16_224
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 10
    increment: 10

    logger_type: tensorboard
    # test_epoch: 10

    note: batchwise_prompt

######### Method's Hyperparameters #########
special:
    gamma: 0.1
    # mode: '' # default:true

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        vit_base_patch16_224:
            img_size: 224
            opt_type: sgd
            epochs: 200 #170
            lrate: 0.1
            scheduler: multi_step
            milestones: [60,120,170]
            lrate_decay: 0.1
            batch_size: 32 # 128
            weight_decay: 0.0005
            num_workers: 4