######### Basic Settings #########
basic:
    device: '1'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: cifar100
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: wa
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet32
    pretrained: false
    save_models: false # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 2000
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    # apply_nme: false

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 20
    increment: 20
    
    # test_epoch: 10

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 2

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    cifar100: 
        resnet32:
            opt_type: sgd
            init_epochs: 200 #200
            init_lrate: 0.1
            init_scheduler: multi_step
            init_milestones: [60,120,170]
            init_lrate_decay: 0.1
            init_weight_decay: 0.0005

            epochs: 170 #170
            lrate: 0.1
            scheduler: multi_step
            milestones: [49, 63]
            lrate_decay: 0.2
            batch_size: 128
            weight_decay: 0.0005
            num_workers: 4

            
