######### Basic Settings #########
basic:
    device: '1'
    seed: [1993] # icarl 官方代码给的种子是 1993

    # Dataset Choises: cifar100, cifar100, imagenet100, imagenet1000, tinyimagenet,
    # skin7, sd198(also known as skin40), mymedmnist
    dataset: skin40
    shuffle: true

    # Method Choises: icarl, end2end, dr, ucir, bic, lwm, podnet, mas, joint， finetune
    method: wa
    method_type: multi_steps
    # eval_metric Choises: acc, recall
    eval_metric: acc

    # Backbone Choises: resnet18, resnet18_cbam, cosine_resnet18, 
    # resnet32, cosine_resnet32, resnet34, cosine_resnet34, resnet50
    backbone: resnet18
    pretrained: false
    save_models: true # if true, programm will save model's weights during incremental train

    ######### Exampler Hyperparameters #########
    memory_size: 200
    fixed_memory: false
    sampling_method: herding # herding, random, closest_to_mean 

    # apply_nme: false

    ######### Task Settings, unimportant in Joint #########
    # for some datasets(e.g. MedMNist), this will be ignored
    split_dataset: true
    init_cls: 5
    increment: 5
    
    note: buffer200

######### Method's Hyperparameters #########
special:
    incre_type: cil
    T: 2

######### Experiment Settings for Datasets #########
options:
    # experiment settings for cifar100
    skin40: 
        resnet18:
            img_size: 224

            epochs: 200 #200
            batch_size: 32
            num_workers: 4
            
            opt_type: sgd
            lrate: 0.01
            weight_decay: 0.0005
            opt_mom: 0.9

            scheduler: multi_step
            milestones: [60,120,170]
            lrate_decay: 0.1
